
app_name: 'testModule'
project_name: 'testProject'
project_version: '0.1'

logging:
  level: DEBUG
  format: '%(levelname)s %(asctime)s  %(message)s'
  message_format: '%(project_name)s:%(project_version)s %(app_id)s %(_filename)s:%(_lineno)d [%(tags)s] '

  filters:
    trans:
      tag: 'TRANS:'   # tag 过滤
  handlers:
    - type: file
      enable: true
      filename: 'server.log'
      encoding: 'UTF-8'
      max_bytes: 67108864 # 64MB
      backup_count: 10

    - type: console
      enable: true



http_trace: #自动日志记录
  level: DEBUG
  request:
    options:
      header:  false
      body:  true
      max_size: 500 # 最大数据包长度
    urls:
      - match: '/'
      - match: 'zoo/cat'
        body:  true

  response:
    options:
      header:  false
      body:  true
      max_size: 500 # 最大数据包长度
    urls:
      - match: '/'
      - match: 'zoo/cat'
        body:  true



datasources:
  - name: 'mongodb'
    class: 'mantis.fundamental.nosql.mongo.Datasource'
    host: 'mongodb'
    port: 27017
    dbname:
    user:
    password:
    enable: true

  - name: 'zk_1'
    type: 'zookeeper'
    enable: false
    hosts: 'localhost:2181'
    root: '/camel'

  - name: 'redis'
    class: 'mantis.fundamental.redis.datasource.Datasource'
    host: 'redis'
    port: 6379
    password: ''
    db: 0
    enable: true

message_brokers:
  - name: 'kafka_1'
    class: 'mantis.fundamental.kafka.MessageBroker'
    enable: false
    hosts: 'localhost:9092'
    zookeepers: 'localhost:2181'
    channels:
      - name: 'test'
        group: 'abcdef'  # simple_consumer if group is null
        handler:  'access.kafka.test.get_message' # last unit< get_message> is function object
        enable: true
        type: 'queue'

  - name: 'redis'
    class: 'mantis.fundamental.redis.broker.MessageBroker'
    host: 'redis'
    port: 6379
    password: ''
    db: 0
    enable: true
    channels:
      - name: 'ctp_contract_tick_queue'
#        handler: 'get_message'
        enable: true
        type: 'queue' # or queue

services:
  - name: 'http'
    class: 'mantis.fundamental.flask.service.FlaskService'
    enable: true
    block: false
    cfgs:
      SQLALCHEMY_DATABASE_URI : 'sqlite:////tmp/test.db'
      SQLALCHEMY_BINDS:
      SQLALCHEMY_TRACK_MODIFICATIONS : true
      SQLALCHEMY_COMMIT_ON_TEARDOWN : true
      SECRET_KEY : "abc"
      TEMPLATES_AUTO_RELOAD: true
      DEBUG: true
      SEND_FILE_MAX_AGE_DEFAULT: 0
    http:
#      host : '172.16.109.237'
      host : '127.0.0.1'
      port : 25100
      threaded: false
      debug: true
      websocket: true

    blueprints:
      - package: 'http'
        url: '/'
        name: 'http'
        register: true
        modules:
          - name: 'views'
            url: 'console'
            routes:
              - url: '/'                    # url name
                name: 'index'   # function name
                methods: 'GET'
              - url: '/orders'                    # url name
                name: 'orders'   # function name
                methods: 'GET'
          - name: 'api'
            url: 'api/m'
            routes:
              - url: '/ticket'           # 用户微信登录
                name: 'get_ticket'       #
                methods: 'POST,GET'

              - url: '/device'        # 用户添加设备
                name: 'add_device'
                methods: 'POST'

              - url: '/device'          # 更新设备信息
                name: 'update_device'
                methods: 'PUT'

              - url: '/device'        # 删除设备
                name: 'remove_device'
                methods: 'DELETE'

              - url: '/device'            # 获取设备详情
                name: 'get_device_info'
                methods: 'GET'

              - url: '/device/list'            # 获取设备列表详情
                name: 'get_device_list'
                methods: 'GET'

              - url: '/share-device'            # 创建共享设备
                name: 'create_share_device'
                methods: 'POST'

              - url: '/share-device'            # 删除共享设备
                name: 'remove_share_device'
                methods: 'DELETE'

              - url: '/share-device/take'            # 用户添加共享设备
                name: 'take_share_device'
                methods: 'POST'

              - url: '/share-device'            # 用户查询共享设备
                name: 'get_share_device_info'
                methods: 'GET'

              - url: '/share-device/list'            # 用户查询共享设备
                name: 'get_share_device_list'
                methods: 'GET'

              - url: '/device/pos/last'            # 用户查询位置信息
                name: 'get_last_position'
                methods: 'GET'

              - url: '/device/pos/trace'            # 用户查询共享设备
                name: 'get_position_path'
                methods: 'GET'

              - url: '/device/config'            # 用户查询设备配置信息
                name: 'get_device_config'
                methods: 'GET'

              - url: '/device/config'            # 用户设置设备配置信息
                name: 'set_device_config'
                methods: 'PUT'

              - url: '/device/fence'            # 用户设置设备配置信息
                name: 'get_device_fence'
                methods: 'GET'

              - url: '/device/fence'            # 用户设置围栏信息
                name: 'set_device_fence'
                methods: 'PUT'

              - url: '/command/audio/start'            # 用户设置设备配置信息
                name: 'cmd_start_audio_record'
                methods: 'POST'

              - url: '/command/position-now-gps'            # 用户设置设备配置信息
                name: 'cmd_position_now_gps'
                methods: 'GET,POST'

              - url: '/command/position-now-lbs'            # 用户设置设备配置信息
                name: 'cmd_position_now_lbs'
                methods: 'GET,POST'

              - url: '/command/position-now'            # 用户设置设备配置信息
                name: 'cmd_position_now'
                methods: 'GET,POST'

              - url: '/command/shutdown'            # 用户设置设备配置信息
                name: 'cmd_shutdown'
                methods: 'GET,POST'

              - url: '/command/reboot'            # 用户设置设备配置信息
                name: 'cmd_reboot'
                methods: 'GET,POST'

              - url: '/audio/list'            #
                name: 'get_audio_record_list'
                methods: 'GET'

              - url: '/audio'            #  /audio/?audio_id=1123123123
                name: 'get_audio_content'
                methods: 'GET'


  - name:       'main'
    id:     'location-adapter'
    enable:     true
    class:      'main.MainService'

    fanout:
      - name: 'switch0'
        channels:
#          - 'redis/con/queue'
          - 'redis/concox_device_message/pubsub'
      - name: 'logging'
        channels:
          - 'redis/trade.log.{service_type}/queue'
          - 'redis/trade.log.{service_type}.{service_id}/pubsub'
      - name: 'strategy_logging'
        channels:
          - 'redis/trade.strategy.log/queue'
          - 'redis/trade.strategy.log.pub/pubsub'

    command_controllers:
      - name: 'gt03'
        class: 'mantis.BlueEarth.vendor.concox.gt03.command.CommandController'

    location_server_api_command: 'http://localhost:19002/api/command'






# qpid-receive -b localhost:5672 -a "mq_test;{create:always,node:{type:queue,durable:true}}"






